#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

api_login_check:
  path: /api/login_check
