
services:
  database:
    container_name: databaseTech
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootAdmin
      MYSQL_DATABASE: databaseEmpty
      MYSQL_USER: userAdmin
      MYSQL_PASSWORD: databaseAdmin33
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-volume/mysql:/data
    ports:
      - "3306:3306"

  node:
    container_name: nodeTech
    build:
        context: ./app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    tty: true


  nginx:
    container_name: nginxTech
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./app:/var/www/app
      - ./backEnd:/var/www/backEnd
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database


  php:
    container_name: phpTech
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./backEnd:/var/www/backEnd
    depends_on:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

  phpmyadmin:
    container_name: phpmyadminTech
    image: phpmyadmin/phpmyadmin
    environment:
       PMA_ARBITRARY: 1
    ports:
      - '8081:80'
    depends_on:
      - database

volumes:
  dbdata:
